services:
  - type: web
    name: trendywear-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
